termux-shared/src/main/java/com/termux/shared/android/AndroidUtils.java
Add isString, isEmpty, isREL boolean variables to the method. Now we can
check the if statement's condition more easily.
=> refactor: Add Explaining Variables at appendPropertyToMarkdownIfSet()

termux-shared/src/main/java/com/termux/shared/android/PermissionUtils.java
result != PERMISSION_GRANTED -> boolean permissionGranted
context instanceof App..Activity -> boolean isApp..Activity
context instanceof Activity -> booelean isActivity
=> Changed: Refactor if statement condition with explaining variables

app/src/main/java/com/termux/app/TermuxService.java
The code  has two methods and variable name isn't good. so it needs to refactor codes. `getAction`, `chooseAction` are extracted. The code is figured out easily to rename variables
=> refactor: extract variable and extract method  from `onStartCommand()`

termux-shared/src/main/java/com/termux/shared/logger/Logger.java
Since if statements for logging were too complicated, refactored those
statements into `switch-cases`. Refactored `boolean` expressions for
comparing `CUURENT_LOG_LEVEL` into explaining variables.
=> Changed: Refactor `logMessage()` from `Logger.java` with `switch-case`

app/src/main/java/com/termux/app/TermuxService.java
`releaseWakeLockAndWifiLock()` extracted method is figured out easily.
=> refactor: extract method in function`actionReleaseWakeLock()`

termux-shared/src/main/java/com/termux/shared/shell/ShellUtils.java
pid "-1" stands for invalid pid. So added local variable that stands for
invalid pid.
=> Changed: Add explaining variable to `getPid()` in `ShellUtils.java`

app/src/main/java/com/termux/app/fragments/settings/termux/DebuggingPreferencesFragment.java
Lines of code are 11. so it need to reduce them. so try to extract method.
=> refactor: extract method from `setLogLevelListPreferenceData()` to `setLogLevelListPreferenceData()`

app/src/main/java/com/termux/app/terminal/TermuxTerminalSessionClient.java
Extract method and Modify  function call  in TermuxTerminalSessionClient.java
=> Refactor/termux terminal session client.java

termux-shared/src/main/java/com/termux/shared/termux/extrakeys/ExtraKeysInfo.java
Variable `jobject` -> `jsonObject`
Variable `popupJobject` -> `popupJSONObject`
=> Changed: Fixed Typo in `ExtraKeysInfo.java`

app/src/main/java/com/termux/app/datastore/termux/DebuggingPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux/TerminalIOPreferencesDataStore.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalIOPreferencesFragment.java
The result is that lines of code are reduced and McCabe Cyclomatic Complexity (CC) is reduced.
=> refactor: extract method and change switch case to conditional operator

app/src/main/java/com/termux/app/datastore/termux/DebuggingPreferencesDataStore.java
The result that lines of code is reducecd and McCabe Cyclomatic Complexity (CC) is reduced
=> refactor : extract method and change switch case to conditional operator

app/src/main/java/com/termux/app/datastore/termux/TerminalIOPreferencesDataStore.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalIOPreferencesFragment.java
The result helps maintain adherence to the Single Responsibility Principle. The code of your classes will be more obvious and understandable.
=> refactor: extract class `TerminalIOPreferencesDataStore.java`

app/src/main/java/com/termux/app/datastore/termux/TerminalIOPreferencesDataStore.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalIOPreferencesFragment.java
Lines of code and McCabe Cyclomatic Complexity (CC) are reducend
=> refactor: extract method `isDisability()`

app/src/main/java/com/termux/app/datastore/termux/TerminalIOPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux/TerminalViewPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux_api/DebuggingPreferencesDataStore.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalIOPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalViewPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux_api/DebuggingPreferencesFragment.java
the name of original class is duplicated but the content is different.  `DebuggingPreferencesDataStore.java` is duplicated. so delete it.
=> refactor: delete duplicated class `DebuggingPreferencesDataStore.java` in `termux_api/DebuggingPreferencesFragment.java`

app/src/main/java/com/termux/app/datastore/termux/TerminalIOPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux/TerminalViewPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux_api/DebuggingPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux_float/DebuggingPreferencesDataStore.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalIOPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalViewPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux_api/DebuggingPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux_float/DebuggingPreferencesFragment.java
Lines of code and McCabe Cyclomatic Complexity (CC) are reduced.
=> refactor: extract class `DebuggingPreferencesDataStore.java`

app/src/main/java/com/termux/app/datastore/termux/TerminalIOPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux/TerminalViewPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux_api/DebuggingPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux_float/DebuggingPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux_tasker/DebuggingPreferencesDataStore.java, app/src/main/java/com/termux/app/datastore/termux_widget/DebuggingPreferencesDataStore.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalIOPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux/TerminalViewPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux_api/DebuggingPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux_float/DebuggingPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux_tasker/DebuggingPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/termux_widget/DebuggingPreferencesFragment.java
Lines of code and McCabe Cyclomatic Complexity (CC) are reduced.
=> refactor: extract method and change switch to conditional operator

termux-shared/src/main/java/com/termux/shared/net/socket/local/LocalSocketRunConfig.java
Since `getLogString()` and `getMarkdownString()` has same log-appeding
structure, added `getLogVariableList()` which returns a list of
`Pair<String, Object>` that contains variables for creating logs.
=> Added: Add `getLogVariableList()` at `LocalSocketRunConfig.java`

termux-shared/src/main/java/com/termux/shared/reflection/ReflectionUtils.java
=> Refactor: ReflectionUtils

app/src/main/java/com/termux/app/terminal/TermuxSessionsListViewController.java
In function `getView()`, Since the method is too long, the method is extracted by function.
=> Refactor/termuxSessionsListViewController.java - Extract Method

termux-shared/src/main/java/com/termux/shared/net/socket/local/PeerCred.java
Add `getLogVariableList()` and refactor `getLogString()` and `getMarkDownString()` with it.
=> Refactor/peer cred.java

termux-shared/src/main/java/com/termux/shared/errors/Errno.java
Reverts rubinstory/termux-app#66
=> Revert "Added: Add `ErrnoBuilder` for `Errno.java`"

app/src/main/java/com/termux/app/fragments/settings/RootPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/configureTermuxAPIPreference.java, app/src/main/java/com/termux/app/fragments/settings/configureTermuxPreference.java
Apply Template method for `configureTermuxPreference`
and delete orginal code about  `configureTermuxAPIPreference()`
=> Added: extract class `configureTermuxAPIPreference()` 

app/src/main/java/com/termux/app/fragments/settings/RootPreferencesFragment.java, app/src/main/java/com/termux/app/fragments/settings/configureTermuxFloatPreference.java
Apply Template method for `configureTermuxPreference`
delete orginal code about  `configureTermuxFloatPreference()`
fix about thread in `configureTermuxAPIPreference.java`
=> Added: extract class `configureTermuxFloatPreference()`

app/src/main/java/com/termux/app/fragments/settings/configureTermuxTaskerPreference.java
Apply Template method for `configureTermuxPreference`
delete orginal code about  `configureTermuxTaskerPreference()`
=> Added: extract class `configureTermuxTaskerPreference()`

terminal-view/src/main/java/com/termux/view/textselection/CursorController.java, terminal-view/src/main/java/com/termux/view/textselection/TextSelectionCursorController.java, terminal-view/src/main/java/com/termux/view/textselection/TextSelectionHandleLeftView.java, terminal-view/src/main/java/com/termux/view/textselection/TextSelectionHandleRightView.java, terminal-view/src/main/java/com/termux/view/textselection/TextSelectionHandleView.java
make `TextSelectionHandleView()` to abstract class
`TextSelectionHandlerLeftView()` and `TextSelectionHandlerRightView()` extends it.
=> Changed: Apply Template method on `TextSelectionHandleView()`

termux-shared/src/main/java/com/termux/shared/shell/StreamGobbler.java, termux-shared/src/main/java/com/termux/shared/shell/command/runner/app/AppShell.java
- `StreamGobbler.java`
- Add a new inner class `StreamGobblerBuilder` for
`StreamGobbler.java`. Now inner class will do the same job as
previous constructors.
- `AppShell.java`
- Replace calling `StreamGobbler` constructors with calling methods
of `StreamGobblerBuilder`.
=> Added|Changed: Add `StreamGobblerBuilder` for `StreamGobbler.java`

termux-shared/src/main/java/com/termux/shared/net/socket/local/LocalSocketRunConfig.java, termux-shared/src/main/java/com/termux/shared/net/socket/local/PeerCred.java, termux-shared/src/main/java/com/termux/shared/net/socket/local/StringGenerator/LocalSocketRunConfigStringGenerator.java, termux-shared/src/main/java/com/termux/shared/net/socket/local/StringGenerator/PeerCredStringGenerator.java, termux-shared/src/main/java/com/termux/shared/net/socket/local/StringGenerator/StringGenerator.java
`PeerCredStringGenerator.java` and
`LocalSocketRunConfigStringGenerator.java`
- `StringGenerator.java`
- Add a new abstract class. Now this new class will be the super
class of all the other {Something}StringGenerator. This class will
provide a Strategy Pattern for `getLogString()` and
`getMarkdownString()` methods.
- `PeerCredStringGenerator`, `LocalSocketRunConfigStringGenerator`
- Add a new Strategy Pattern class who extends `StringGenerator`
class. Those classes provides a string generating strategies for
`PeerCred` and `LocalSocketRunConfig`.
=> Added|Changed: Add `StringGenerator.java`,

termux-shared/src/main/java/com/termux/shared/android/AndroidUtils.java, termux-shared/src/main/java/com/termux/shared/android/TimeStampUtils/BasicTimeStamp.java, termux-shared/src/main/java/com/termux/shared/android/TimeStampUtils/MilliSecondLocalTimeStamp.java, termux-shared/src/main/java/com/termux/shared/android/TimeStampUtils/MilliSecondUTCTimeStamp.java, termux-shared/src/main/java/com/termux/shared/android/TimeStampUtils/TimeStampUtils.java, termux-shared/src/main/java/com/termux/shared/crash/CrashHandler.java, termux-shared/src/main/java/com/termux/shared/models/ReportInfo.java, termux-shared/src/main/java/com/termux/shared/shell/command/result/ResultSender.java, termux-shared/src/main/java/com/termux/shared/termux/plugins/TermuxPluginUtils.java
Add a new Template Method Pattern class which extends `TimeStampUtils` class.
Those classes provides a time stamp template methods
for `CrashHandler`, `ReportInfo`,`ResultSender`, `TermuxPluginUtils`.
=> Added|Changed: Apply Template Method pattern in TimeStampUtils.

termux-shared/src/main/java/com/termux/shared/net/socket/local/LocalClientSocket.java
Added `getObjectString()` to LocalClientSocket and refactored
`getLogString(), getMarkdownString()` with it.
=> Changed: Refactored `LocalClientSocket`

termux-shared/src/main/java/com/termux/shared/net/socket/local/LocalClientSocket.java, termux-shared/src/main/java/com/termux/shared/net/socket/local/LocalSocketRunConfig.java
Added `getObjectString()` to LocalSocketRunConfig and refactored
`getLogString()`, `getMarkdownString()` with it.
=> Changed: Refactored `LocalSocketRunConfig`

app/src/main/java/com/termux/app/TermuxService.java
Each of methods is extract as class.
add: `Command.class`, `Button.class`
=> changed: implement Command Pattern on `killAllTermuxExecutionCommands()`

app/src/main/java/com/termux/app/TermuxService.java
it was implemented as lots of methods. so it was complex code.
it become simple code. as implement facade pattern.
add class `actionServiceExecuteFacade`
=> changed: implement Facade Pattern on `actionServiceExecute()`

termux-shared/src/test/java/com/termux/shared/markdown/MarkdownUtilsTest.java, termux-shared/src/test/java/com/termux/shared/termux/data/TermuxUrlUtilsTest.java
Validates that it produces an appropriate markdown string for the input.
=> Added unit tests for `MarkdownUtils`

termux-shared/build.gradle, termux-shared/src/test/java/com/termux/shared/models/ReportInfoTest.java
add test case for ReportInfo.java
=> TestReport info.java

termux-shared/src/test/java/com/termux/shared/logger/LoggerTest.java
- testGetMessageAndStackTraceStringForNullString()
- Purpose
- Check when string is null
- Input
- Logger.getMessageAndStackTraceString (null, null), (null, Throwable)
- Expected
- (null, null) = null
- (null, Throwable) = Logger.getStackTraceString(Throwable)
- testGetMessageAndStackTraceStringForString()
- Purpose
- Check when string is given
- Input
- Logger.getMessageAndStackTraceString ("message", null), ("message", Throwable)
- Expected
- ("message" null) = "message"
- ("message", Throwable) = "message:\n" + Logger.getStackTraceString(throwable)
=> Added: Added: Add test case for Logger.getMessageAndStackStraceString()

termux-shared/src/test/java/com/termux/shared/android/AndroidUtilsTest.java
Do unit testing in AndroidUtils
=> TestAndroidUtils.java
